const express = require('express');
const router = express.Router();
const workflowBuilderService = require('../services/workflow-builder-service');
const logger = require('../utils/logger');

/**
 * Feature 12, 13 & 14: No-Code Workflow Builder REST API
 *
 * Static routes (node-types, stats, validate, sample-employees, ai-generate) MUST appear
 * before dynamic /:id routes to avoid Express param collisions.
 */

// GET /api/workflow-builder/node-types — List all 11 node types
router.get('/node-types', (req, res) => {
    try {
        const types = workflowBuilderService.getNodeTypes();
        res.status(200).json({ success: true, nodeTypes: types, data: types });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error fetching node types:', err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/stats — Summary stats
router.get('/stats', (req, res) => {
    try {
        const stats = workflowBuilderService.getStats();
        res.status(200).json({ success: true, stats, data: stats });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error fetching stats:', err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/sample-employees — Pre-seeded test catalog
router.get('/sample-employees', (req, res) => {
    try {
        const employees = workflowBuilderService.getSampleEmployees();
        res.status(200).json({ success: true, employees, data: employees });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error fetching sample employees:', err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder/validate — Validate raw canvas JSON
router.post('/validate', (req, res) => {
    try {
        const { canvas, nodes, connections, edges } = req.body || {};
        const validation = workflowBuilderService.validateCanvas(canvas || { nodes, connections: connections || edges });
        res.status(200).json({ success: true, validation });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error validating canvas:', err);
        res.status(400).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder/ai-generate — AI Automation Creator (Natural Language to Draft Workflow)
router.post('/ai-generate', (req, res) => {
    try {
        const { prompt, options } = req.body || {};
        if (!prompt) {
            return res.status(400).json({ success: false, error: 'A natural-language prompt is required.' });
        }

        const result = workflowBuilderService.createWorkflowFromPrompt(prompt, options);
        res.status(200).json({
            success: true,
            workflow: result.workflow,
            data: result.workflow,
            nodeChain: result.nodeChain,
            explanation: result.explanation,
            confidence: result.confidence,
            summary: result.summary,
            message: 'Draft workflow generated by Kylrx AI (Review mode active).'
        });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error generating AI workflow:', err);
        res.status(400).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder — List all workflows
router.get('/', (req, res) => {
    try {
        const workflows = workflowBuilderService.listWorkflows();
        res.status(200).json({ success: true, workflows, data: workflows, total: workflows.length });
    } catch (err) {
        logger.error('[WorkflowBuilderAPI] Error listing workflows:', err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder — Save (create) a new workflow
router.post('/', async (req, res) => {
    try {
        const workflowData = req.body || {};
        const actor = req.body?.actor || 'HR Administrator';
        if (!workflowData.name) {
            return res.status(400).json({ success: false, error: 'Workflow name is required.' });
        }

        const workflow = workflowBuilderService.saveWorkflow(workflowData, null, { actor });
        res.status(201).json({
            success: true,
            workflow,
            data: workflow,
            message: `Workflow '${workflow.name}' saved successfully.`
        });
    } catch (err) {
        const isValidation = err.message.includes('Validation failed');
        logger.error('[WorkflowBuilderAPI] Error saving workflow:', err);
        res.status(isValidation ? 422 : 500).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/:id — Get full workflow
router.get('/:id', (req, res) => {
    try {
        const workflow = workflowBuilderService.getWorkflow(req.params.id);
        if (!workflow) {
            return res.status(404).json({ success: false, error: `Workflow '${req.params.id}' not found.` });
        }
        res.status(200).json({ success: true, workflow, data: workflow });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error fetching workflow '${req.params.id}':`, err);
        res.status(404).json({ success: false, error: err.message });
    }
});

// PUT /api/workflow-builder/:id — Update existing workflow
router.put('/:id', async (req, res) => {
    try {
        const workflowData = req.body || {};
        const actor = req.body?.actor || 'HR Administrator';
        const workflow = workflowBuilderService.saveWorkflow(workflowData, req.params.id, { actor });
        res.status(200).json({
            success: true,
            workflow,
            data: workflow,
            message: `Workflow '${workflow.name}' updated successfully.`
        });
    } catch (err) {
        const isValidation = err.message.includes('Validation failed');
        logger.error(`[WorkflowBuilderAPI] Error updating workflow '${req.params.id}':`, err);
        res.status(isValidation ? 422 : 500).json({ success: false, error: err.message });
    }
});

// DELETE /api/workflow-builder/:id — Delete workflow
router.delete('/:id', (req, res) => {
    try {
        const deleted = workflowBuilderService.deleteWorkflow(req.params.id, { actor: req.body?.actor || 'HR Administrator' });
        if (!deleted) {
            return res.status(404).json({ success: false, error: `Workflow '${req.params.id}' not found.` });
        }
        res.status(200).json({ success: true, deleted: true, message: 'Workflow deleted successfully.' });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error deleting workflow '${req.params.id}':`, err);
        res.status(404).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder/:id/activate & /versions/publish — Promote tested draft to Active
router.post(['/:id/activate', '/:id/versions/publish'], async (req, res) => {
    try {
        const { actor, versionNumber } = req.body || {};
        const workflow = await workflowBuilderService.publishWorkflowVersion(req.params.id, versionNumber, { actor });
        res.status(200).json({
            success: true,
            workflow,
            data: workflow,
            message: `Workflow '${workflow.name}' (v${workflow.activeVersionNumber}) published and active.`
        });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error activating workflow '${req.params.id}':`, err);
        res.status(400).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder/:id/versions/:versionNumber/rollback — Rollback to previous version
router.post('/:id/versions/:versionNumber/rollback', async (req, res) => {
    try {
        const { actor } = req.body || {};
        const workflow = await workflowBuilderService.rollbackWorkflow(req.params.id, req.params.versionNumber, { actor });
        res.status(200).json({
            success: true,
            workflow,
            data: workflow,
            message: `Workflow rolled back to v${workflow.version}.`
        });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error rolling back workflow '${req.params.id}':`, err);
        res.status(400).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/:id/versions — List all versions
router.get('/:id/versions', (req, res) => {
    try {
        const workflow = workflowBuilderService.getWorkflow(req.params.id);
        if (!workflow) {
            return res.status(404).json({ success: false, error: `Workflow '${req.params.id}' not found.` });
        }
        res.status(200).json({
            success: true,
            workflowId: workflow.id,
            activeVersionNumber: workflow.activeVersionNumber,
            currentVersion: workflow.version,
            versions: workflow.versions || []
        });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error fetching versions for '${req.params.id}':`, err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// POST /api/workflow-builder/:id/test-run — Simulate workflow execution with employee/sample data
router.post('/:id/test-run', (req, res) => {
    try {
        const { employeeId, mockData, actor } = req.body || {};
        const simulation = workflowBuilderService.testRunWorkflow(req.params.id, { employeeId, mockData, actor });
        res.status(200).json({ success: true, simulation, data: simulation });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error simulating workflow '${req.params.id}':`, err);
        res.status(400).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/:id/execution-logs — List execution runs (success, failure, retry, error reasons)
router.get('/:id/execution-logs', (req, res) => {
    try {
        const { status, limit } = req.query || {};
        const logs = workflowBuilderService.listExecutionLogs(req.params.id, { status, limit: parseInt(limit, 10) || 50 });
        res.status(200).json({
            success: true,
            workflowId: req.params.id,
            totalLogs: logs.length,
            executionLogs: logs,
            data: logs
        });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error fetching execution logs for '${req.params.id}':`, err);
        res.status(500).json({ success: false, error: err.message });
    }
});

// GET /api/workflow-builder/:id/audit-trail — Immutable user change audit logs
router.get('/:id/audit-trail', (req, res) => {
    try {
        const logs = workflowBuilderService.listAuditLogs(req.params.id);
        res.status(200).json({
            success: true,
            workflowId: req.params.id,
            totalAuditEntries: logs.length,
            auditTrail: logs,
            data: logs
        });
    } catch (err) {
        logger.error(`[WorkflowBuilderAPI] Error fetching audit trail for '${req.params.id}':`, err);
        res.status(500).json({ success: false, error: err.message });
    }
});

module.exports = router;
